### ISSUE TITLE
Can we use ts-ebml to implement the functionality of $ mkvmerge -w -o full.webm 1.webm + N.webm ?

### ISSUE THREAD

**Issue by guest271314** [legokichi/ts-ebml#26]
Can we use ts-ebml to implement the functionality of 

```$ mkvmerge -w -o full.webm 1.webm + N.webm``` ?

First attempt to filter `SimpleBlock`s

```
          const decoder = new EBML.Decoder();
          const encoder = new EBML.Encoder();
          const reader = new EBML.Reader();
          const tools = EBML.tools;
          console.log(tools, reader, encoder, decoder);
          const ebmlElms = decoder.decode(ab);
          
          reader.drop_default_duration = true;

          ebmlElms.forEach((elm) => {
            reader.read(elm);
          });

          reader.stop();

          console.log(reader.metadatas, reader.duration, reader.cues);

          console.log(ebmlElms.filter(({name:n}) => n === "SimpleBlock"));
```

How do we append the `SimpleBlock`s from e.g., webm_file_1 to the `Cluster` of webm_file_2, change values of `timecode` elements to be sequential (webm_file_1 through webm_file_2) and reset `Duration` to create a new webm file (webm_file_3) having `Duration` value set to the sum of webm_file_1 and webm_file_2?

**Comment by guest271314** [comment]
@legokichi FWIW https://github.com/guest271314/native-messaging-mkvmerge/. Can `ts-ebml` as currently written, or with adjustments, can be utilized to achieve the same output?

**Comment by legokichi** [comment]
ts-ebml is just a simple ebml parser, not a high level muxer.
off course you can write remuxer carefully like the mkvmerge cli yourself.
but i cannot it because i dont have enough muxer specs knowledge.

**Comment by rahulbansal16** [comment]
@guest271314 I checked the link that you shared. My understanding after watching it is to maintain the audio and video stream and mux it into the WebM format. Am I correct? 
The demo (https://rawgit-now.netlify.app/davedoesdev/webm-muxer.js/main/demo.html) link shared in the documentation fails to run because of the MediaStreamTrackProcessor that requires chrome 93 and some experimental features flag.
This might not work for my use case.
Did you find any way to modify the WebM container via the ts-ebml repo?

**Comment by rahulbansal16** [comment]
My approach is :-
The chunks from the datavailable callback can be collected in an array like
``` 
var recordedBlobs = [];
mediaRecorder.ondataavailable = event => {
recordedBlobs.push(event.data); }
```
The unwanted chunks can be discarded

```
var e = recordedBlobs.length
recordedBlobs = recordedBlobs.slice(e-10, e)
var video =  new Blob(recordedBlobs , {
            type: 'video/webm'
        });
```
This is not recognized as the WebM file since the EBML header is missing.
I artificially replaced the header like this.
 
```
var e = recordedBlobs.length
var header = recordedBlobs[0]
var blobWithHeader = [header]
var trimmedblobs = recordedBlobs.slice(e-10, e)
blobWithHeader.concat(trimmedBlobs)
var video =  new Blob(blobWithHeader, {
            type: 'video/webm'
        });
```
The above change makes the file WebM, but it messes up the playback, etc.

I realized that the SimpleBlocks inside the Clusters are responsible for playing the video and If I could copy the parts of the EBML Header and append them to trimmedBlobs. I can make the video work.

I took an EBML dump of the header and of the blobWithHeader and found that they were identical. 
![image](https://user-images.githubusercontent.com/8466045/131210548-146a4709-1ad7-41be-8f9a-e6c53ce0b7e4.png)
![image](https://user-images.githubusercontent.com/8466045/131210559-e3bc218f-6aca-4836-93a5-07e97ff8aa8c.png)

except there were some elements in the end which the MKV tool was not able to make sense of and was giving the error.
**Known element, but invalid at this position: Simple block (ID: 0xa3)**
![image](https://user-images.githubusercontent.com/8466045/131210777-516d9c74-6af4-443b-a1be-43fd3c24f765.png)

I am assuming that the above might be SimpleBlockElement but their timecode and duration might not be continuous with the header's simple block elements duration and timecode.

I am assuming that if I can somehow read the remaining SimpleBlockElements and manually change the timeCode and duration continuous then the whole file should work.

I tried decoding the trimmedBlobs by the EBML.deocder but it fails with some size field not known. I feel some simple Block parser can be used to convert the trimmedBlobs data.

@legokichi What do you think about my approach? Am I on the correct path.

**Comment by guest271314** [comment]
> The unwanted chunks can be discarded

For that use case I would suggest exploring the branches of https://github.com/guest271314/MediaFragmentRecorder.

**Comment by guest271314** [comment]
You can use https://github.com/dominikhlbg/vp8-webm-javascript-decoder to extract all images from a WebM file, see https://github.com/guest271314/screenshot.
